version: '3.5'

services:
  db:
    image: postgres:14
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
  token-cleaner:
    build:
      context: .
      dockerfile: Dockerfile-token-cleaner
    depends_on:
      - db
    volumes:
      - ./tmp/log/cron.log:/var/log/cron.log
  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    ports:
      - ${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}
    depends_on:
      - db
  api:
    image: node:12
    container_name: network-api
    working_dir: /api
    volumes:
      - .:/api/
    ports:
      - ${APP_HOST_PORT}:${APP_CONTAINER_PORT}
    depends_on:
      - db
    command: "npm run start:dev"
