version: '3.5'

services:
  db:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db
  api:
    image: node:12
    container_name: network-api
    working_dir: /api
    volumes:
      - .:/api/
    ports:
      - ${APP_PORT}:3001
    depends_on:
      - db
    command: "npm run start:dev"